[DEFAULT]
# the default build command
builder = debuild
# use pristine-tar
pristine-tar = True
# use upstream branch for upstream sources
upstream-branch = main
# use debian branch for debian sources
debian-branch = debian

[buildpackage]
# use dpkg-buildpackage instead of debuild
buildpackage = dpkg-buildpackage
# ignore new upstream versions
ignore-new = True

[dch]
# use git-dch for changelog generation
dch = git-dch
# git-dch options
git-author = True
# ignore regex for changelog generation
ignore-regex = ^(?!(debian|changelog))

[import-orig]
# use gbp import-orig for importing upstream sources
import-orig = gbp import-orig
# upstream version regex
upstream-version = %(version)s

[pq]
# use gbp pq for patch management
pq = gbp pq
